/*
 * File: app/view/allUsersGrid.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('cstt.view.allUsersGrid', {
    extend: 'cstt.view.ui.allUsersGrid',
    alias: 'widget.allUsersGrid',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    },

    onAddClick: function(button, e, options) {
        var user = Ext.widget('newStaffForm');
    },

    onRefreshClick: function(button, e, options) {
        this.store.load();
    },

    onEditClick: function(button, e, options) {
		// Zeige das Formular an (Benutzer)	
            selectStaff = this.getView().getSelectionModel().getSelection()[0];

            if (selectStaff) {
                var staffWindow = Ext.widget('newStaffForm');

                staffWindow.setTitle('Benutzer editieren ...');
                staffWindow.staffUserGridExtJSID = this.getId();
                staffWindow.down('form').getForm().loadRecord(selectStaff);	

                staffWindow.down('#save').hide();
                staffWindow.down('#edit').show();		

            }
            else {
                Ext.MessageBox.show({
                    title: 'Hinweis',
                    msg: 'Bitte w&auml;hlen Sie zuerst einen Benutzer aus!',
                    buttons: Ext.MessageBox.OK,
                    icon: Ext.MessageBox.INFO
                });
            }
    }

});