%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosTransactions_NotSubtransaction
%% Source: /private/tmp/erlang-Y5fv/otp-OTP_R16B02/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.3.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosTransactions_NotSubtransaction').
-ic_compiled("4_3_3").


-include("CosTransactions.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosTransactions/NotSubtransaction:1.0",
                   "NotSubtransaction",[]}.

%% returns id
id() -> "IDL:omg.org/CosTransactions/NotSubtransaction:1.0".

%% returns name
name() -> "CosTransactions_NotSubtransaction".



