/*
 * File: app/view/ui/showOneTicket.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cstt.view.ui.showOneTicket', {
    extend: 'Ext.panel.Panel',
    requires: [
        'cstt.view.actionCommentGrid',
        'cstt.view.attachmentGrid'
    ],

   autoScroll: true,
    layout: {
        type: 'border'
    },
    title: '',
    dataRecord: 'null',
    couchDBDocID: 'null',
    jsonTicket: 'null',
    anchor: '100%',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    itemId: 'topToolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            iconCls: 'menu_show',
                            text: 'Aktion',
                            tooltip: 'Bitte Aktion ausw&auml;hlen ...',
                            menu: {
                                xtype: 'menu',
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        icon: 'images/icons/comment_add.png',
                                        text: 'Kommentar',
                                        listeners: {
                                            click: {
                                                fn: me.actionHandleComment,
                                                scope: me
                                            }
                                        }
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Eskalation (2nd Level)',
                                        iconCls: 'bullet_wrench',
                                        listeners: {
                                            click: {
                                                fn: me.actionEscalation2ndLevel,
                                                scope: me
                                            }
                                        }
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Eskalation (Vertrieb)',
                                        iconCls: 'basket_go',
                                        listeners: {
                                            click: {
                                                fn: me.actionEscalationSales,
                                                scope: me
                                            }
                                        }
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'In Bearbeitung (Support)',
                                        iconCls: 'user_edit',
                                        listeners: {
                                            click: {
                                                fn: me.actionHandleSupport,
                                                scope: me
                                            }
                                        }
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'In Bearbeitung (Kunde)',
                                        iconCls: 'user_suit',
                                        listeners: {
                                            click: {
                                                fn: me.actionHandleCustomer,
                                                scope: me
                                            }
                                        }
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'L&ouml;sungsvorschlag an Kunde',
                                        iconCls: 'page_white_text',
                                        listeners: {
                                            click: {
                                                fn: me.actionSolutionToCustomer,
                                                scope: me
                                            }
                                        }
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Entwicklung (Derbystrasse)',
                                        iconCls: 'keyboard',
                                        listeners: {
                                            click: {
                                                fn: me.actionHandleDevelopment,
                                                scope: me
                                            }
                                        }
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Entwicklung (Hauptplatz)',
                                        iconCls: 'keyboard',
                                        listeners: {
                                            click: {
                                                fn: me.actionHandleDevelopmentOffice,
                                                scope: me
                                            }
                                        }
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Ticket zur&uuml;ckstellen',
                                        iconCls: 'arrow_redo',
                                        listeners: {
                                            click: {
                                                fn: me.actionHandleDeferredTicket,
                                                scope: me
                                            }
                                        }
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Ticket schlie&szlig;en',
                                        iconCls: 'lock',
                                        listeners: {
                                            click: {
                                                fn: me.actionHandleCloseTicket,
                                                scope: me
                                            }
                                        }
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'buttonEditTicket',
                            iconCls: 'database_edit',
                            text: 'Editieren',
                            tooltip: 'Editieren ...',
                            listeners: {
                                click: {
                                    fn: me.DisplayEditTicketWindow,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ],
            items: [
               {
                    xtype: 'tabpanel',
                    height: 222,
                    itemId: 'tabpanelUp',
                    activeTab: 0,
                    region: 'north',
                    deferredRender: false,
                    items: [
                        {
                            xtype: 'panel',
                            itemId: 'ticketPanel',
                            autoScroll: true,
                            layout: {
                                type: 'column'
                            },
                            title: 'Ticket',
                            tabConfig: {
                                xtype: 'tab',
                                tooltip: 'Ticket'
                            },
                            listeners: {
                                activate: {
                                    fn: me.onTicketPanelActivate,
                                    scope: me
                                }
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    itemId: 'columnTicketLeft',
                                    padding: 10,
                                    width: 550,
                                    items: [
                                        {
                                            xtype: 'displayfield',
                                            itemId: 'date',
                                            fieldLabel: 'Datum/Zeit',
                                            labelStyle: 'font-weight:bold;',
                                            width: 500,
                                            labelWidth: 130
                                        },
                                        {
                                            xtype: 'displayfield',
                                            itemId: 'companyName',
                                            name: 'companyName',
                                            fieldLabel: 'Firma',
                                            labelStyle: 'font-weight:bold;',
                                            width: 500,
                                            labelWidth: 130
                                        },
                                        {
                                            xtype: 'displayfield',
                                            itemId: 'contactName',
                                            fieldLabel: 'Kontaktperson',
                                            labelStyle: 'font-weight:bold;',
                                            width: 500,
                                            labelWidth: 130
                                        },
                                        {
                                            xtype: 'displayfield',
                                            itemId: 'contact_request',
                                            fieldLabel: 'Kontaktaufnahme',
                                            labelStyle: 'font-weight:bold;',
                                            width: 500,
                                            labelWidth: 130
                                        },
                                        {
                                            xtype: 'displayfield',
                                            itemId: 'title',
                                            fieldLabel: 'Kurzbeschreibung',
                                            labelStyle: 'font-weight:bold;',
                                            width: 500,
                                            labelWidth: 130
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    itemId: 'columnTicketRight',
                                    padding: 10,
                                    width: 500,
                                    items: [
                                        {
                                            xtype: 'displayfield',
                                            itemId: 'ticketNumber',
                                            fieldLabel: 'Ticket-Nr.',
                                            width: 500,
                                            labelStyle: 'font-weight:bold;'
                                        },
                                        {
                                            xtype: 'displayfield',
                                            itemId: 'ticket_type',
                                            fieldLabel: 'Typ',
                                            width: 500,
                                            labelStyle: 'font-weight:bold;'
                                        },
                                        {
                                            xtype: 'displayfield',
                                            itemId: 'status',
                                            fieldLabel: 'Status',
                                            width: 500,
                                            labelStyle: 'font-weight:bold;'
                                        },
                                        {
                                            xtype: 'displayfield',                                           
                                            itemId: 'creatorNameTicket',
                                            fieldLabel: 'Ersteller',
                                            width: 500,
                                            labelStyle: 'font-weight:bold;'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'description',
                            autoScroll: true,
                            bodyPadding: 10,
                            title: 'Beschreibung',
                            overflow: 'auto',
                            tabConfig: {
                                xtype: 'tab',
                                tooltip: 'Beschreibung'
                            },
                            listeners: {
                                activate: {
                                    fn: me.onDescriptionActivate,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'panel',
                            itemId: 'panelApproach',
                            autoScroll: true,
                            bodyPadding: 10,
                            title: 'L&ouml;sungsvorschlag an Kunde',
                            overflow: 'auto',
                            tabConfig: {
                                xtype: 'tab',
                                tooltip: 'L&ouml;sungsvorschlag an Kunde'
                            },
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    itemId: 'topToolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            text: 'Zu Qualifizierte L&ouml;sung &uuml;bernehmen',
                                            tooltip: 'Zu Qualifizierte L&ouml;sung &uuml;bernehmen ...',
                                            listeners: {
                                                click: {
                                                    fn: me.confirmQualifiedSolution,
                                                    scope: me
                                                }
                                            }
                                        }
                                    ]
                                }
                            ],
                            listeners: {
                                activate: {
                                    fn: me.onPanelApproachActivate,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'panel',
                            itemId: 'qualifiedSolution',
                            autoScroll: true,
                            bodyPadding: 10,
                            title: 'Qualifizierte L&ouml;sung',
                            overflow: 'auto',
                            tabConfig: {
                                xtype: 'tab',
                                tooltip: 'Qualifizierte L&ouml;sung ...'
                            },
                            listeners: {
                                activate: {
                                    fn: me.onQualifiedSolutionActivate,
                                    scope: me
                                }
                            }
                        }
                    ]
                },
                {
                    xtype: 'tabpanel',
                    border: 'false',
                    region: 'center',
                    height: 280,
                    itemId: 'tabpanelBottom',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            title: 'Aktionen',
                            tabConfig: {
                                xtype: 'tab',
                                tooltip: 'Aktionen'
                            },
                            layout: 'anchor',
                            items: [
                                {
                                    xtype: 'actionCommentGrid',
                                    height: 250,
                                    autoScroll: true,
                                    overflow: 'auto',
                                    itemId: 'oneTicketActionGrid',
                                  	store: new Ext.data.Store({
										model: 'cstt.model.actionModel',
										  sorters: [
									        {
									            property : 'createdOn',
									            direction: 'DESC'
									        }
									    ]			
									 })
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: 'Dateianh&auml;nge',
                            tabConfig: {
                                xtype: 'tab',
                                tooltip: 'Dateianh&auml;nge'
                            },
                            layout: 'anchor',
                            items: [
                                {
                                    xtype: 'attachmentGrid',
                                    height: 250,
                                    autoScroll: true,
                                    overflow: 'auto',
                                    itemId: 'attachmentsToTicketGrid',
                                    store: new Ext.data.Store({
										model: 'cstt.model.ticketAttachmentsModel'
									})
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    actionHandleComment: function(item, e, options) {
    },

    actionEscalation2ndLevel: function(item, e, options) {
    },

    actionEscalationSales: function(item, e, options) {
    },

    actionHandleSupport: function(item, e, options) {
    },

    actionHandleCustomer: function(item, e, options) {
    },

    actionSolutionToCustomer: function(item, e, options) {
    },

    actionHandleDevelopment: function(item, e, options) {
    },
    
    actionHandleDevelopmentOffice: function(item, e, options) { 
    },
    
    actionHandleDeferredTicket: function(item, e, options) {
    },

    actionHandleCloseTicket: function(item, e, options) {
    },

    DisplayEditTicketWindow: function(button, e, options) {
    },

    onTicketPanelActivate: function(abstractcomponent, options) {
    },

    onDescriptionActivate: function(abstractcomponent, options) {
    },

    confirmQualifiedSolution: function(button, e, options) {
    },

    onPanelApproachActivate: function(abstractcomponent, options) {
    },

    onQualifiedSolutionActivate: function(abstractcomponent, options) {
    }

});