%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventChannelAdmin_ConsumerAdmin
%% Source: /private/tmp/erlang-Y5fv/otp-OTP_R16B02/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.3.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCHANNELADMIN_CONSUMERADMIN_HRL).
-define(COSEVENTCHANNELADMIN_CONSUMERADMIN_HRL, true).




-endif.


