%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyFilter_FilterAdmin
%% Source: /private/tmp/erlang-Y5fv/otp-OTP_R16B02/lib/cosNotification/src/CosNotifyFilter.idl
%% IC vsn: 4.3.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYFILTER_FILTERADMIN_HRL).
-define(COSNOTIFYFILTER_FILTERADMIN_HRL, true).




-endif.


