%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyChannelAdmin_ConsumerAdmin
%% Source: /private/tmp/erlang-Y5fv/otp-OTP_R16B02/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.3.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCHANNELADMIN_CONSUMERADMIN_HRL).
-define(COSNOTIFYCHANNELADMIN_CONSUMERADMIN_HRL, true).




-endif.


