%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyComm_StructuredPullSupplier
%% Source: /private/tmp/erlang-Y5fv/otp-OTP_R16B02/lib/cosNotification/src/CosNotifyComm.idl
%% IC vsn: 4.3.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCOMM_STRUCTUREDPULLSUPPLIER_HRL).
-define(COSNOTIFYCOMM_STRUCTUREDPULLSUPPLIER_HRL, true).




-endif.


