/*
 * File: app/view/newStaffForm.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('cstt.view.newStaffForm', {
    extend: 'cstt.view.ui.newStaffForm',
    alias: 'widget.newStaffForm',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    },

    onCancelClick: function(button, e, options) {
        this.close();
    },
    
    onEditClick: function(button, e, options) {
    	 if (this.down('form').getForm().isValid()) {			


            //	var record = this.down('form').getRecord();
            //	var values = this.down('form').getValues();
            //	record.set(values);		
            //	record.commit();


            var record = this.down('form').getRecord();		

            //console.log(record);

            this.down('form').getForm().updateRecord(record);		 


            Ext.getCmp(this.staffUserGridExtJSID).getStore().sync();
            Ext.getCmp(this.staffUserGridExtJSID).getStore().removeAll();

            this.close();

            Ext.MessageBox.show({
                title: 'Status',
                msg: '&Auml;nderungen wurden gespeichert.',
                buttons: Ext.MessageBox.OK,
                scope: this,
                fn: function() {
                    Ext.example.msg('Status', 'Synchronisierung');	
                    Ext.getCmp(this.staffUserGridExtJSID).onRefreshClick();
                }	
            });
        }
        else {
            // Zeige Warnung - nicht alle Felder ausgefuellt
            boxWarningRequiredFields();
        }
    },

    onSaveClick: function(button, e, options) {
        // Formularüberprüfung
        if (this.down('form').getForm().isValid()) {
            // Wait Message anzeigen	
            Ext.MessageBox.wait('Speichern ...', 'Bitte warten ...');

            Ext.Ajax.request({
                waitMsg: 'Bitte warten...',
                method: 'POST',
                url: '../../',
                scope: this,
                // Header auf application/json setzen - CouchDB
                headers: {
                    'Content-Type': 'application/json; charset=utf-8'
                },
                // Die Formular-Eingaben uebergeben
                params: Ext.JSON.encode(this.down('form').getForm().getValues()),
                success: function(){
                    // Fenster schliessen
                    this.close();

                    // Wait Message verbergen			
                    Ext.MessageBox.hide();

                    Ext.data.StoreManager.lookup('allStaffStore').load();		

                },
                failure: function(){
                    // Wait Message verbergen			
                    Ext.MessageBox.hide();
                    // Zeige Fehler während des Speicherns			
                    boxErrorDuringSaving();			  
                }
            });
        }
        else {		
            // Zeige Warnung - nicht alle Felder ausgefüllt
            boxWarningRequiredFields();	
        }
    }

});