%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CORBA
%% Source: /private/tmp/erlang-Y5fv/otp-OTP_R16B02/lib/orber/src/CORBA.idl
%% IC vsn: 4.3.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_CORBA_HRL).
-define(OE_CORBA_HRL, true).




-endif.


