/*
 * File: app/view/ui/contactsToCustomerWindow.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cstt.view.ui.contactsToCustomerWindow', {
    extend: 'Ext.window.Window',

    height: 400,
    width: 1100,
    layout: {
        type: 'fit'
    },
    title: 'My Window',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    itemId: 'bottomToolbar',
                    ui: 'footer',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'closeButton',
                            text: 'Schließen',
                            listeners: {
                                click: {
                                    fn: me.onCloseClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ], 
           
            items: [{
						xtype: 'contactPersonGrid',
						overflow: 'auto',
						autoScroll: true,
						store: new Ext.data.Store({
					 	model: 'cstt.model.contactGridModel',
						  sorters: [
					        {
					            property : 'companyConvert',
					            direction: 'ASC'
					        }
					    ]
						}),	
						title: ''
				}]
        });

        me.callParent(arguments);
    },

    onWindowAfterRender: function(abstractcomponent, options) {
    },

    onCloseClick: function(button, e, options) {
    }

});