/*
 * File: app/view/ui/allUsersGrid.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cstt.view.ui.allUsersGrid', {
    extend: 'Ext.grid.Panel',

    height: 500,
    autoScroll: true,
    title: 'Benutzerübersicht',
    store: 'allStaffStore',
    overflow: 'auto',
    anchor: '100%',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: '_id',
                    text: 'ID'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: '_rev',
                    text: 'rev'
                },
                {
                    xtype: 'gridcolumn',
                    width: 220,
                    dataIndex: 'staff_name',
                    text: 'Name'
                },
                {
                    xtype: 'gridcolumn',
                    width: 220,
                    dataIndex: 'username',
                    text: 'Benutzername'
                },
                {
                    xtype: 'gridcolumn',
                    width: 350,
                    dataIndex: 'staff_email',
                    text: 'E-Mail Adresse'
                }
            ],
            viewConfig: {
                emptyText: 'Keine Benutzer vorhanden ...',
                loadingText: 'Lade alle Benutzer ...'
            },
            dockedItems: [
                {
                    xtype: 'toolbar',
                    itemId: 'topToolbar',
                    width: 645,
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'reloadButton',
                            iconCls: 'x-tbar-loading',
                            text: 'Aktualisieren',
                            tooltip: 'Aktualisieren ...',
                            listeners: {
                                click: {
                                    fn: me.onRefreshClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            iconCls: 'user_add',
                            text: 'Benutzer hinzufügen',
                            tooltip: 'Einen neuen Benutzer hinzufügen ...',
                            listeners: {
                                click: {
                                    fn: me.onAddClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            iconCls: 'user_edit',
                            text: 'Benutzer editieren',
                            tooltip: 'Editiert den ausgewählten Benutzer ...',
                            listeners: {
                                click: {
                                    fn: me.onEditClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onRefreshClick: function(button, e, options) {
    },

    onAddClick: function(button, e, options) {
    },

    onEditClick: function(button, e, options) {
    }

});