/*
 * File: app/view/ui/overviewVersionGrid.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cstt.view.ui.overviewVersionGrid', {
    extend: 'Ext.grid.Panel',

    height: 500,
    autoScroll: true,
    title: 'Versionsverwaltung',
    store: 'versionManagementStore',
    anchor: '100%',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: 220,
                    dataIndex: 'component',
                    text: 'Komponente'
                },
                {
                    xtype: 'gridcolumn',
                    width: 220,
                    dataIndex: 'version',
                    text: 'Version'
                }
            ],
            viewConfig: {
                emptyText: 'Keine Einträge in der Versionsverwaltung ...',
                loadingText: 'Lade die Versionsverwaltung ...'
            },
            dockedItems: [
                {
                    xtype: 'toolbar',
                    itemId: 'topToolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            iconCls: 'x-tbar-loading',
                            text: 'Aktualisieren',
                            tooltip: 'Aktualisieren ...',
                            listeners: {
                                click: {
                                    fn: me.onRefreshClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            iconCls: 'add',
                            text: 'Version hinzufügen',
                            tooltip: 'Fügt eine neue Version hinzu ...',
                            listeners: {
                                click: {
                                    fn: me.onAddClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            iconCls: 'remove',
                            text: 'Version löschen',
                            tooltip: 'Löscht die ausgewählte Version...',
                            listeners: {
                                click: {
                                    fn: me.onDeleteClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onRefreshClick: function(button, e, options) {
    },

    onAddClick: function(button, e, options) {
    },

    onDeleteClick: function(button, e, options) {
    }

});