/*
 * File: app/view/ui/newStaffForm.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cstt.view.ui.newStaffForm', {
    extend: 'Ext.window.Window',

    autoShow: true,
    height: 320,
    width: 482,
    activeItem: 0,
    layout: {
        type: 'anchor'
    },
    bodyPadding: 5,
    staffUserGridExtJSID: 'null',
    title: 'Neuen Benutzer hinzufügen ...',
    widget: 'widget.newStaffForm',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    itemId: 'bottomToolbar',
                    ui: 'footer',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'save',
                            text: 'Speichern',
                            listeners: {
                                click: {
                                    fn: me.onSaveClick,
                                    scope: me
                                }
                            }
                        }, 
                        {
                            xtype: 'button',
                            hidden: true,
                            itemId: 'edit',
                            text: 'Änderungen speichern',
                            listeners: {
                                click: {
                                    fn: me.onEditClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            text: 'Abbrechen',
                            listeners: {
                                click: {
                                    fn: me.onCancelClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'form',
                    itemId: 'staffForm',
                    bodyPadding: 10,
                    frameHeader: false,
                    title: '',
                    items: [
                        {
                            xtype: 'textfield',
                            width: 320,
                            name: 'username',
                            fieldLabel: 'Benutzername',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            width: 320,
                            name: 'staff_name',
                            fieldLabel: 'Vor- / Nachname',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            width: 380,
                            name: 'staff_email',
                            fieldLabel: 'E-Mail',
                            allowBlank: false,
                            vtype: 'email'
                        },
                        {
                            xtype: 'fieldset',
                            height: 135,
                            title: 'Benutzerrechte',
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    name: 'isAdmin',
                                    fieldLabel: 'Administratorrechte',
                                    labelWidth: 130,
                                    boxLabel: '',
                                    inputValue: 'true',
                                    uncheckedValue: 'false',
                                    anchor: '100%'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    name: 'isTCOB',
                                    fieldLabel: 'TCOB-Rechte',
                                    labelWidth: 130,
                                    boxLabel: '',
                                    inputValue: 'true',
                                    uncheckedValue: 'false',
                                    anchor: '100%'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    name: 'isSupport',
                                    fieldLabel: 'Support-Rechte',
                                    labelWidth: 130,
                                    boxLabel: '',
                                    inputValue: 'true',
                                    uncheckedValue: 'false',
                                    anchor: '100%'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    name: 'isSales',
                                    fieldLabel: 'Vertrieb-Rechte',
                                    labelWidth: 130,
                                    boxLabel: '',
                                    inputValue: 'true',
                                    uncheckedValue: 'false',
                                    anchor: '100%'
                                }
                            ]
                        },
                        {
                            xtype: 'hiddenfield',
                            name: 'type',
                            value: 'staff',
                            fieldLabel: 'Label',
                            anchor: '100%'
                        },
                        {
                        	xtype: 'hiddenfield',
                        	name: 'password',
                        	// md5 cordaware
                        	value: '4cc11c70c5d2ef66ccf070d2f6490522'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onSaveClick: function(button, e, options) {
    },
    
    onEditClick: function(button, e, options) {
    },

    onCancelClick: function(button, e, options) {
    }

});