/*
 * File: app/view/ui/showOneActionInWindow.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cstt.view.ui.showOneActionInWindow', {
    extend: 'Ext.window.Window',

    height: 415,
    width: 720,
    maximizable: true,
    bodyPadding: 5,
    title: 'Aktion:',
    dataRecord: 'null',
    
    layout: {
        align: 'stretch',
        type: 'vbox'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    itemId: 'bottomToolbar',
                    ui: 'footer',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Schließen',
                            listeners: {
                                click: {
                                    fn: me.onCloseClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'displayfield',
                    itemId: 'action',
                    submitValue: false,
                    fieldLabel: 'Aktion',
                    labelStyle: 'font-weight:bold;'
                },
                {
                    xtype: 'displayfield',
                    itemId: 'date',
                    submitValue: false,
                    fieldLabel: 'Erstellt am',
                    labelStyle: 'font-weight:bold;'
                },
                {
                    xtype: 'displayfield',
                    itemId: 'staffName',
                    submitValue: false,
                    fieldLabel: 'Verfasser',
                    labelStyle: 'font-weight:bold;'
                },
                {
                	xtype: 'displayfield',
                	fieldLabel: 'E-Mail',
                	itemId: 'emailTo',
                	value: 'keine Benachrichtigung',
                    labelStyle: 'font-weight:bold;'
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    itemId: 'comment',
                    autoScroll: true,
                    bodyPadding: 5,
                    overflow: 'auto'
                }
            ]
        });

        me.callParent(arguments);
    },

    onCloseClick: function(button, e, options) {
    }

});