/*
 * File: app/model/versionToCustomerModel.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cstt.model.versionToCustomerModel', {
    extend: 'Ext.data.Model',

    idProperty: '_id',

    fields: [
        {
            name: '_id',
            type: 'string'
        },
        {
            name: '_rev',
            type: 'string'
        },
        {
            name: 'component',
            type: 'string'
        },
        {
            dateFormat: 'Y-m-d',
            name: 'patchDate',
            type: 'date'
        },
        {
            name: 'version',
            type: 'string'
        },
        {
            defaultValue: 'historyVersionCustomer',
            name: 'type',
            type: 'string'
        }
    ],

    proxy: {
        type: 'rest',
        api: {
            create: '../../',
            read: '_view/versionToCustomer?include_docs=true',
            update: '../../',
            destroy: '../../'
        },
        directionParam : '',
        filterParam : '',
        groupParam : '',
        limitParam : '',
        pageParam : '',
        sortParam : '',
        startParam : '',
        url: 'http://localhost:5984',
        reader: {
            type: 'json',
            idProperty: '_id',
            root: 'rows',
            successProperty: 'ok',
            totalProperty: 'total_rows',
            record: 'doc'
        }
    }
});