/*
 * File: app/store/ticket24HoursStore.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('cstt.store.ticket24HoursStore', {
    extend: 'cstt.store.base.ticketCurrentStore',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({}, cfg)]);
    },

    onStoreBeforeLoad: function(store, operation, options) {
    	store.getProxy().extraParams = '';
        store.getProxy().limitParam = '';
        store.getProxy().startParam = '';
        
        var currentDate = Math.round((new Date().getTime())/1000);
        var beginDate = currentDate-(1*60*60*24);
        store.getProxy().api.read = '_view/ticket24Hours?include_docs=true&startkey="'+beginDate+'"&endkey="'+currentDate+'"';
    }

});