%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_cos_naming_ext
%% Source: /private/tmp/erlang-Y5fv/otp-OTP_R16B02/lib/orber/COSS/CosNaming/cos_naming_ext.idl
%% IC vsn: 4.3.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COS_NAMING_EXT_HRL).
-define(OE_COS_NAMING_EXT_HRL, true).




-endif.


