
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "cstt": "app",
  " Ext.Msg": "ext/src/window/MessageBox.js",
  "Ext": "ext/src",
  "Ext.rtl.EventObjectImpl": "ext/src/rtl/EventObject.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "cstt.model.ticketCurrentModel": [],
  "cstt.view.ui.allTicketsGrid": [],
  "cstt.store.allCustomersStore": [],
  "cstt.view.showOneTicket": [],
  "cstt.model.actionStatusModel": [],
  "cstt.view.ui.uploadWindow": [],
  "cstt.view.allTicketsGrid": [],
  "cstt.view.ui.newStaffForm": [],
  "cstt.model.countryModel": [],
  "Ext.ux.DataView.DragSelector": [],
  "cstt.store.base.ticketTypeStore": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "cstt.view.descriptionToCurrentTicket": [],
  "cstt.view.ui.ticketPieChart": [],
  "cstt.store.base.languageStore": [],
  "cstt.store.base.chartTicketStore": [],
  "cstt.store.base.salutationStore": [],
  "cstt.store.actionstoTicketHistory": [],
  "Ext.ux.PreviewPlugin": [],
  "Ext.ux.ajax.SimXhr": [],
  "cstt.view.resellerCombo": [],
  "Ext.ux.CellDragDrop": [],
  "cstt.view.ui.showOneTicket": [],
  "Ext.ux.ajax.Simlet": [],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "cstt.view.attachmentGrid": [],
  "cstt.view.customerTicketChart": [],
  "cstt.store.base.ticketAttachmentsStore": [],
  "cstt.store.searchStore": [],
  "cstt.store.base.ticketsToCustomerStore": [],
  "cstt.store.chartTicketStore": [],
  "Ext.ux.event.Recorder": [],
  "cstt.model.versionToCustomerModel": [],
  "cstt.store.salutationStore": [],
  "cstt.store.ticketAttachmentsStore": [],
  "cstt.model.contactGridModel": [],
  "cstt.view.deleteFileForm": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "cstt.store.ticketCurrentStore": [],
  "cstt.view.uploadWindow": [],
  "Ext.ux.IFrame": [],
  "cstt.store.ticket24HoursStore": [],
  "cstt.store.versionManagementStore": [],
  "cstt.store.base.ticket24HoursStore": [],
  "Ext.ux.form.SearchField": [],
  "Ext.ux.dd.CellFieldDropZone": [],
  "cstt.view.ticketPieChart": [],
  "cstt.store.contactGridStore": [],
  "cstt.model.staffGridModel": [],
  "cstt.view.ticketTypeComboBox": [],
  "cstt.model.versionManagementModel": [],
  "cstt.store.base.versionManagementStore": [],
  "cstt.view.csttHtmlEditor": [],
  "cstt.view.newTicketForm": [],
  "cstt.store.actionstoTicketCurrent": [],
  "cstt.store.allStaffStore": [],
  "cstt.view.ui.allUsersGrid": [],
  "cstt.view.ui.actionCommentGrid": [],
  "cstt.controller.customer": [],
  "Ext.ux.FieldReplicator": [],
  "cstt.store.base.versionCustomerStore": [],
  "cstt.view.newStaffForm": [],
  "Ext.ux.grid.filter.ListFilter": [],
  "cstt.store.base.ticketHistoryStore": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "cstt.view.customerGrid": [],
  "cstt.model.allCustomersModel": [],
  "Ext.ux.GMapPanel": [],
  "cstt.view.ui.versionCustomerGrid": [],
  "cstt.store.base.ticketProjectStore": [],
  "cstt.store.base.allStaffStore": [],
  "cstt.view.ui.searchWindow": [],
  "Ext.ux.GroupTabPanel": [],
  "cstt.view.ui.ticketTypeComboBox": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "cstt.model.companyComboBoxModel": [],
  "cstt.view.contactRequestComboBox": [],
  "Ext.ux.layout.Center": [],
  "cstt.view.editTicketWindow": [],
  "cstt.view.contactsToCustomerWindow": [],
  "Ext.ux.DataView.Animated": [],
  "cstt.view.ui.customerGrid": [],
  "cstt.store.ticketHistoryStore": [],
  "cstt.view.contactPersonGrid": [],
  "cstt.controller.csttController": [],
  "cstt.view.csttViewport": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "cstt.view.insertImageWindow": [],
  "cstt.view.ui.attachmentGrid": [],
  "cstt.view.staffTicketChart": [],
  "cstt.store.base.commentStore": [],
  "cstt.view.ui.companyComboBox": [],
  "cstt.store.base.storeComponentServerClient": [],
  "cstt.view.ui.detailsToCustomerWindow": [],
  "Ext.ux.event.Player": [],
  "cstt.model.yearModel": [],
  "Ext.ux.ToolbarDroppable": [],
  "cstt.view.exportTickets": [],
  "cstt.view.ui.createContactWindow": [],
  "cstt.store.companyConvertStore": [],
  "cstt.view.saveChartButton": [],
  "Ext.ux.DataView.Draggable": [],
  "cstt.store.base.allCustomersStore": [],
  "cstt.view.ui.overviewVersionGrid": [],
  "Ext.ux.TabCloseMenu": [],
  "cstt.view.overviewVersionGrid": [],
  "cstt.view.ui.ticketsToCustomerGrid": [],
  "Ext.ux.grid.filter.DateTimeFilter": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "cstt.store.base.positionStore": [],
  "cstt.store.actionStore": [],
  "cstt.view.ui.descriptionToCurrentTicket": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [],
  "cstt.view.ui.deleteFileForm": [],
  "cstt.view.ticketsToCustomerGrid": [],
  "cstt.view.resellerWindow": [],
  "cstt.store.commentStore": [],
  "cstt.store.ticketTypeStore": [],
  "cstt.store.countryStore": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.grid.TransformGrid": [],
  "cstt.store.base.companyComboBoxStore": [],
  "cstt.view.companyComboBox": [],
  "cstt.view.versionCustomerGrid": [],
  "cstt.store.customerTicketChartStore": [],
  "cstt.view.loginWindow": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "Ext.ux.event.Driver": [],
  "cstt.model.staffChartTicketModel": [],
  "cstt.view.ui.actionWindow": [],
  "cstt.store.base.actionstoTicketCurrent": [],
  "cstt.model.salutationModel": [],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "cstt.view.createCustomerWindow": [],
  "cstt.store.deleteFileStore": [],
  "cstt.model.componentServerClientModel": [],
  "cstt.model.deleteFileModel": [],
  "cstt.store.versionCustomerStore": [],
  "cstt.store.base.actionstoTicketHistory": [],
  "cstt.view.ui.loginWindow": [],
  "cstt.view.createContactWindow": [],
  "Ext.ux.event.RecorderManager": [],
  "cstt.store.contactRequestStore": [],
  "cstt.store.base.actionStore": [],
  "Ext.ux.ProgressBarPager": [],
  "cstt.store.base.contactRequestStore": [],
  "cstt.store.allStaffEmailStore": [],
  "cstt.model.languageModel": [],
  "cstt.store.base.countryStore": [],
  "Ext.ux.ajax.SimManager": [],
  "cstt.view.ui.showOneActionInWindow": [],
  "cstt.store.base.allStaffEmailStore": [],
  "cstt.store.base.ticketCurrentStore": [],
  "cstt.store.yearStore": [],
  "Ext.ux.TabScrollerMenu": [],
  "cstt.store.base.ticketDeferredStore": [],
  "cstt.view.Viewport": [],
  "cstt.store.actionStatusStore": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "cstt.store.base.companyConvertStore": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "Ext.ux.TreePicker": [],
  "cstt.view.ui.createCustomerWindow": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ],
  "cstt.store.storeComponentServerClient": [],
  "Ext.ux.BoxReorderer": [],
  "cstt.store.staffTicketChartStore": [],
  "Ext.ux.grid.filter.Filter": [],
  "cstt.view.showOneActionInWindow": [],
  "Ext.ux.GroupTabRenderer": [],
  "cstt.store.positionStore": [],
  "cstt.view.ui.csttViewport": [],
  "cstt.view.actionWindow": [],
  "cstt.view.ui.editTicketWindow": [],
  "cstt.store.editionProductStore": [],
  "cstt.view.ui.contactRequestComboBox": [],
  "cstt.store.ticketDeferredStore": [],
  "cstt.view.createVersionWindow": [],
  "cstt.store.ticketsToCustomerStore": [],
  "cstt.model.chartTicketModel": [],
  "Ext.ux.DataView.LabelEditor": [],
  "cstt.store.base.editionProductStore": [],
  "cstt.view.allUsersGrid": [],
  "Ext.ux.grid.filter.StringFilter": [],
  "cstt.model.ticketAttachmentsModel": [],
  "cstt.model.actionModel": [],
  "cstt.view.yearComboBox": [],
  "cstt.model.customerChartTicketModel": [],
  "cstt.view.ui.contactPersonGrid": [],
  "cstt.store.addOnsStore": [],
  "cstt.model.resellerModel": [],
  "cstt.store.base.contactGridStore": [],
  "cstt.view.detailsToCustomerWindow": [],
  "cstt.store.languageStore": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "cstt.store.companyComboBoxStore": [],
  "Ext.ux.RowExpander": [],
  "cstt.model.commentModel": [],
  "cstt.store.contactToCompanyStore": [],
  "cstt.model.positionModel": [],
  "cstt.view.searchWindow": [],
  "cstt.view.changePasswordWindow": [],
  "cstt.store.base.contactToCompanyStore": [],
  "cstt.store.ticketProjectStore": [],
  "Ext.ux.event.Maker": [],
  "cstt.controller.tickets": [],
  "cstt.store.base.deleteFileStore": [],
  "cstt.view.ui.createVersionWindow": [],
  "cstt.view.actionCommentGrid": [],
  "cstt.view.ui.newTicketForm": [],
  "Ext.ux.DataTip": [],
  "cstt.store.base.addOnsStore": [],
  "Ext.ux.ajax.JsonSimlet": [],
  "cstt.store.base.searchStore": [],
  "cstt.view.ui.contactsToCustomerWindow": [],
  "cstt.store.base.actionStatusStore": [],
  "cstt.store.resellerStore": []
});
Ext.ClassManager.addNameAliasMappings({
  "cstt.model.ticketCurrentModel": [],
  "cstt.view.ui.allTicketsGrid": [],
  "cstt.store.allCustomersStore": [],
  "cstt.view.showOneTicket": [
    "widget.showOneTicket"
  ],
  "cstt.model.actionStatusModel": [],
  "cstt.view.ui.uploadWindow": [],
  "cstt.view.allTicketsGrid": [
    "widget.allTicketsGrid"
  ],
  "cstt.view.ui.newStaffForm": [],
  "cstt.model.countryModel": [],
  "Ext.ux.DataView.DragSelector": [],
  "cstt.store.base.ticketTypeStore": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "cstt.view.descriptionToCurrentTicket": [
    "widget.descriptionToCurrentTicket"
  ],
  "cstt.view.ui.ticketPieChart": [],
  "cstt.store.base.languageStore": [],
  "cstt.store.base.chartTicketStore": [],
  "cstt.store.base.salutationStore": [],
  "cstt.store.actionstoTicketHistory": [],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "Ext.ux.ajax.SimXhr": [],
  "cstt.view.resellerCombo": [
    "widget.resellerCombo"
  ],
  "Ext.ux.CellDragDrop": [
    "plugin.celldragdrop"
  ],
  "cstt.view.ui.showOneTicket": [],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "cstt.view.attachmentGrid": [
    "widget.attachmentGrid"
  ],
  "cstt.view.customerTicketChart": [
    "widget.customerTicketChart"
  ],
  "cstt.store.base.ticketAttachmentsStore": [],
  "cstt.store.searchStore": [],
  "cstt.store.base.ticketsToCustomerStore": [],
  "cstt.store.chartTicketStore": [],
  "Ext.ux.event.Recorder": [],
  "cstt.model.versionToCustomerModel": [],
  "cstt.store.salutationStore": [],
  "cstt.store.ticketAttachmentsStore": [],
  "cstt.model.contactGridModel": [],
  "cstt.view.deleteFileForm": [
    "widget.deleteFileForm"
  ],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "cstt.store.ticketCurrentStore": [],
  "cstt.view.uploadWindow": [
    "widget.uploadWindow"
  ],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "cstt.store.ticket24HoursStore": [],
  "cstt.store.versionManagementStore": [],
  "cstt.store.base.ticket24HoursStore": [],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "Ext.ux.dd.CellFieldDropZone": [],
  "cstt.view.ticketPieChart": [
    "widget.ticketPieChart"
  ],
  "cstt.store.contactGridStore": [],
  "cstt.model.staffGridModel": [],
  "cstt.view.ticketTypeComboBox": [
    "widget.ticketTypeComboBox"
  ],
  "cstt.model.versionManagementModel": [],
  "cstt.store.base.versionManagementStore": [],
  "cstt.view.csttHtmlEditor": [
    "widget.csttHtmlEditor"
  ],
  "cstt.view.newTicketForm": [
    "widget.newTicketForm"
  ],
  "cstt.store.actionstoTicketCurrent": [],
  "cstt.store.allStaffStore": [],
  "cstt.view.ui.allUsersGrid": [],
  "cstt.view.ui.actionCommentGrid": [],
  "cstt.controller.customer": [],
  "Ext.ux.FieldReplicator": [],
  "cstt.store.base.versionCustomerStore": [],
  "cstt.view.newStaffForm": [
    "widget.newStaffForm"
  ],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "cstt.store.base.ticketHistoryStore": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "cstt.view.customerGrid": [
    "widget.customerGrid"
  ],
  "cstt.model.allCustomersModel": [],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "cstt.view.ui.versionCustomerGrid": [],
  "cstt.store.base.ticketProjectStore": [],
  "cstt.store.base.allStaffStore": [],
  "cstt.view.ui.searchWindow": [],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "cstt.view.ui.ticketTypeComboBox": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "cstt.model.companyComboBoxModel": [],
  "cstt.view.contactRequestComboBox": [
    "widget.contactRequestComboBox"
  ],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "cstt.view.editTicketWindow": [
    "widget.editTicketWindow"
  ],
  "cstt.view.contactsToCustomerWindow": [
    "widget.contactsToCustomerWindow"
  ],
  "Ext.ux.DataView.Animated": [],
  "cstt.view.ui.customerGrid": [],
  "cstt.store.ticketHistoryStore": [],
  "cstt.view.contactPersonGrid": [
    "widget.contactPersonGrid"
  ],
  "cstt.controller.csttController": [],
  "cstt.view.csttViewport": [],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "cstt.view.insertImageWindow": [
    "widget.insertImageWindow"
  ],
  "cstt.view.ui.attachmentGrid": [],
  "cstt.view.staffTicketChart": [
    "widget.staffTicketChart"
  ],
  "cstt.store.base.commentStore": [],
  "cstt.view.ui.companyComboBox": [],
  "cstt.store.base.storeComponentServerClient": [],
  "cstt.view.ui.detailsToCustomerWindow": [],
  "Ext.ux.event.Player": [],
  "cstt.model.yearModel": [
    "model.yearModel"
  ],
  "Ext.ux.ToolbarDroppable": [],
  "cstt.view.exportTickets": [
    "widget.exportTickets"
  ],
  "cstt.view.ui.createContactWindow": [],
  "cstt.store.companyConvertStore": [],
  "cstt.view.saveChartButton": [
    "widget.saveChartButton"
  ],
  "Ext.ux.DataView.Draggable": [],
  "cstt.store.base.allCustomersStore": [],
  "cstt.view.ui.overviewVersionGrid": [],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "cstt.view.overviewVersionGrid": [
    "widget.overviewVersionGrid"
  ],
  "cstt.view.ui.ticketsToCustomerGrid": [],
  "Ext.ux.grid.filter.DateTimeFilter": [
    "gridfilter.datetime"
  ],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "cstt.store.base.positionStore": [],
  "cstt.store.actionStore": [],
  "cstt.view.ui.descriptionToCurrentTicket": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ],
  "cstt.view.ui.deleteFileForm": [],
  "cstt.view.ticketsToCustomerGrid": [
    "widget.ticketsToCustomerGrid"
  ],
  "cstt.view.resellerWindow": [
    "widget.resellerWindow"
  ],
  "cstt.store.commentStore": [],
  "cstt.store.ticketTypeStore": [],
  "cstt.store.countryStore": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.grid.TransformGrid": [],
  "cstt.store.base.companyComboBoxStore": [],
  "cstt.view.companyComboBox": [
    "widget.companyComboBox"
  ],
  "cstt.view.versionCustomerGrid": [
    "widget.versionCustomerGrid"
  ],
  "cstt.store.customerTicketChartStore": [],
  "cstt.view.loginWindow": [
    "widget.loginWindow"
  ],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "Ext.ux.event.Driver": [],
  "cstt.model.staffChartTicketModel": [],
  "cstt.view.ui.actionWindow": [],
  "cstt.store.base.actionstoTicketCurrent": [],
  "cstt.model.salutationModel": [],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "cstt.view.createCustomerWindow": [
    "widget.createCustomerWindow"
  ],
  "cstt.store.deleteFileStore": [],
  "cstt.model.componentServerClientModel": [],
  "cstt.model.deleteFileModel": [],
  "cstt.store.versionCustomerStore": [],
  "cstt.store.base.actionstoTicketHistory": [],
  "cstt.view.ui.loginWindow": [],
  "cstt.view.createContactWindow": [
    "widget.createContactWindow"
  ],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "cstt.store.contactRequestStore": [],
  "cstt.store.base.actionStore": [],
  "Ext.ux.ProgressBarPager": [],
  "cstt.store.base.contactRequestStore": [],
  "cstt.store.allStaffEmailStore": [],
  "cstt.model.languageModel": [],
  "cstt.store.base.countryStore": [],
  "Ext.ux.ajax.SimManager": [],
  "cstt.view.ui.showOneActionInWindow": [],
  "cstt.store.base.allStaffEmailStore": [],
  "cstt.store.base.ticketCurrentStore": [],
  "cstt.store.yearStore": [],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "cstt.store.base.ticketDeferredStore": [],
  "cstt.view.Viewport": [],
  "cstt.store.actionStatusStore": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "cstt.store.base.companyConvertStore": [],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "cstt.view.ui.createCustomerWindow": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ],
  "cstt.store.storeComponentServerClient": [],
  "Ext.ux.BoxReorderer": [],
  "cstt.store.staffTicketChartStore": [],
  "Ext.ux.grid.filter.Filter": [],
  "cstt.view.showOneActionInWindow": [
    "widget.showOneActionInWindow"
  ],
  "Ext.ux.GroupTabRenderer": [
    "plugin.grouptabrenderer"
  ],
  "cstt.store.positionStore": [],
  "cstt.view.ui.csttViewport": [],
  "cstt.view.actionWindow": [
    "widget.actionWindow"
  ],
  "cstt.view.ui.editTicketWindow": [],
  "cstt.store.editionProductStore": [],
  "cstt.view.ui.contactRequestComboBox": [],
  "cstt.store.ticketDeferredStore": [],
  "cstt.view.createVersionWindow": [
    "widget.createVersionWindow"
  ],
  "cstt.store.ticketsToCustomerStore": [],
  "cstt.model.chartTicketModel": [],
  "Ext.ux.DataView.LabelEditor": [],
  "cstt.store.base.editionProductStore": [],
  "cstt.view.allUsersGrid": [
    "widget.allUsersGrid"
  ],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "cstt.model.ticketAttachmentsModel": [],
  "cstt.model.actionModel": [],
  "cstt.view.yearComboBox": [
    "widget.yearComboBox"
  ],
  "cstt.model.customerChartTicketModel": [],
  "cstt.view.ui.contactPersonGrid": [],
  "cstt.store.addOnsStore": [],
  "cstt.model.resellerModel": [
    "model.resellerModel"
  ],
  "cstt.store.base.contactGridStore": [],
  "cstt.view.detailsToCustomerWindow": [
    "widget.detailsToCustomerWindow"
  ],
  "cstt.store.languageStore": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "cstt.store.companyComboBoxStore": [],
  "Ext.ux.RowExpander": [],
  "cstt.model.commentModel": [],
  "cstt.store.contactToCompanyStore": [],
  "cstt.model.positionModel": [],
  "cstt.view.searchWindow": [
    "widget.searchWindow"
  ],
  "cstt.view.changePasswordWindow": [
    "widget.changePasswordWindow"
  ],
  "cstt.store.base.contactToCompanyStore": [],
  "cstt.store.ticketProjectStore": [],
  "Ext.ux.event.Maker": [],
  "cstt.controller.tickets": [],
  "cstt.store.base.deleteFileStore": [],
  "cstt.view.ui.createVersionWindow": [],
  "cstt.view.actionCommentGrid": [
    "widget.actionCommentGrid"
  ],
  "cstt.view.ui.newTicketForm": [],
  "Ext.ux.DataTip": [
    "plugin.datatip"
  ],
  "cstt.store.base.addOnsStore": [],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "cstt.store.base.searchStore": [],
  "cstt.view.ui.contactsToCustomerWindow": [],
  "cstt.store.base.actionStatusStore": [],
  "cstt.store.resellerStore": []
});
