%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosPropertyService_PropertySetDef
%% Source: /private/tmp/erlang-Y5fv/otp-OTP_R16B02/lib/cosProperty/src/CosProperty.idl
%% IC vsn: 4.3.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSPROPERTYSERVICE_PROPERTYSETDEF_HRL).
-define(COSPROPERTYSERVICE_PROPERTYSETDEF_HRL, true).




-endif.


