/*
 * File: app/view/ui/editTicketWindow.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cstt.view.ui.editTicketWindow', {
    extend: 'Ext.window.Window',

    height: 250,
    width: 400,
    title: 'Ticket editieren',
    couchDBTicketDocID: null,
    showOneTicketExtJsID: 'null',
    actionForRequest: 'null',
    jsonTicket: 'null',
    
    layout: {
        type: 'fit'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    itemId: 'bottomToolbar',
                    ui: 'footer',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'edit',
                            text: 'Änderungen speichern',
                            listeners: {
                                click: {
                                    fn: me.onEditClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            text: 'Abbrechen',
                            listeners: {
                                click: {
                                    fn: me.onCancelClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'form',
                    itemId: 'editTicketForm',
                    defaults: {
                        labelWidth: 180,
                        labelAlign: 'top'
                    },
                    bodyPadding: 10
                }
            ]
        });

        me.callParent(arguments);
    },

    onEditClick: function(button, e, options) {
    },

    onCancelClick: function(button, e, options) {
    }

});