/*
 * File: app/view/ui/descriptionToCurrentTicket.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cstt.view.ui.descriptionToCurrentTicket', {
    extend: 'Ext.panel.Panel',

    height: 180,
    autoScroll: true,
    bodyPadding: 5,
    title: 'Beschreibung',
    anchor: '100%',
    overflow: 'auto',

    initComponent: function() {
        var me = this;

        me.callParent(arguments);
    }

});