/*
 * File: app/view/ui/detailsToCustomerWindow.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cstt.view.ui.detailsToCustomerWindow', {
    extend: 'Ext.window.Window',

    height: 250,
    width: 650,
    resizable: false,
    layout: {
        type: 'column'
    },
    title: 'Kundendetails',
    couchDBDocID: 'null',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    itemId: 'bottomToolbar',
                    ui: 'footer',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'closeButton',
                            text: 'Schließen',
                            listeners: {
                                click: {
                                    fn: me.onCloseClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'container',
                    itemId: 'leftContainer',
                    padding: 10,
                    width: 300,
                    items: [
                        {
                            xtype: 'displayfield',
                            itemId: 'street1',
                            fieldLabel: 'Strasse 1',
                            labelStyle: 'font-weight:bold;'
                        },
                        {
                            xtype: 'displayfield',
                            itemId: 'street2',
                            fieldLabel: 'Strasse 2',
                            labelStyle: 'font-weight:bold;'
                        },
                        {
                            xtype: 'displayfield',
                            itemId: 'street3',
                            fieldLabel: 'Strasse 3',
                            labelStyle: 'font-weight:bold;'
                        },
                        {
                            xtype: 'displayfield',
                            itemId: 'city',
                            fieldLabel: 'PLZ / Ort',
                            labelStyle: 'font-weight:bold;'
                        },
                        {
                            xtype: 'displayfield',
                            itemId: 'country',
                            fieldLabel: 'Land',
                            labelStyle: 'font-weight:bold;'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    itemId: 'rightContainer',
                    padding: 10,
                    width: 300,
                    items: [
                        {
                            xtype: 'displayfield',
                            itemId: 'editionProduct',
                            fieldLabel: 'Edition',
                            labelStyle: 'font-weight:bold;'
                        },
                        {
                            xtype: 'displayfield',
                            itemId: 'addOnsProduct',
                            fieldLabel: 'Add Ons',
                            labelStyle: 'font-weight:bold;'
                        },
                        {
                            xtype: 'displayfield',
                            itemId: 'numberOfLicences',
                            fieldLabel: 'Anzahl der Lizenzen',
                            labelStyle: 'font-weight:bold;'
                        },
                        {
                            xtype: 'displayfield',
                            name: 'supportFrom',
                            itemId: 'supportFrom',
                            fieldLabel: 'Support von',
                            labelStyle: 'font-weight:bold;'
                        },
                        {
                            xtype: 'displayfield',
                            name: 'supportTo',
                            itemId: 'supportTo',
                            fieldLabel: 'Support bis',
                            labelStyle: 'font-weight:bold;'
                        },
                        {
                            xtype: 'displayfield',
                            itemId: 'specials',
                            fieldLabel: 'Besonderheiten',
                            labelStyle: 'font-weight:bold;'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onCloseClick: function(button, e, options) {
    }

});