/*
 * File: app/model/ticketAttachmentsModel.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cstt.model.ticketAttachmentsModel', {
    extend: 'Ext.data.Model',

    idProperty: 'filename',

    proxy: {
        type: 'rest',
        api: {
            create: '../../',
            read: '_view/ticketAttachments',
            update: '../../',
            destroy: '../../'
        },
        directionParam : '',
        filterParam : '',
        groupParam : '',
        limitParam : '',
        pageParam : '',
        sortParam : '',
        startParam : '',
        url: 'http://localhost:5984',
        reader: {
            type: 'json',
            idProperty: 'filename',
            root: 'rows',
            successProperty: 'ok',
            totalProperty: 'total_rows',
            record: 'value'
        }
    },

    fields: [
        {
            name: '_id',
            type: 'string'
        },
        {
            name: '_rev',
            type: 'string'
        },
        {
            name: 'filename',
            type: 'string'
        },
        {
            name: 'filesize',
            type: 'int'
        }
    ]
});