%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyComm_StructuredPushConsumer
%% Source: /private/tmp/erlang-Y5fv/otp-OTP_R16B02/lib/cosNotification/src/CosNotifyComm.idl
%% IC vsn: 4.3.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCOMM_STRUCTUREDPUSHCONSUMER_HRL).
-define(COSNOTIFYCOMM_STRUCTUREDPUSHCONSUMER_HRL, true).




-endif.


