/*
 * File: app/view/ui/csttViewport.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cstt.view.ui.csttViewport', {
    extend: 'Ext.container.Viewport',
    requires: [
        'cstt.view.allTicketsGrid',
        'cstt.view.actionCommentGrid',
        'cstt.view.descriptionToCurrentTicket'
    ],

    id: 'viewport',
    autoScroll: true,
    layout: {
        type: 'border'
    },
    overflow: 'auto',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    id: 'centerTabPanel',
                    // AutoDestroy muss auf true sein!
                    autoDestroy: true,
                    defaults: {
                        deferredRender: false,
                        overflow: 'auto'
                    },
                    title: '',
                    activeTab: 0,
                    region: 'center',
                    items: [
                        {
                            xtype: 'panel',
                            itemId: 'currentTicketsTab',
                            listeners: {
                                activate: {
                                    fn: me.onCurrentTicketsTabActive,
                                    scope: me
                                }
                            },
                            autoScroll: true,
                           	layout: {
						        align: 'stretch',
						        type: 'vbox'
						    },
                            title: 'Support Tickets',
                            tabConfig: {
                                xtype: 'tab',
                                tooltip: 'Aktuelle Support Tickets'
                            },
                            items: [
                                {
                                    xtype: 'allTicketsGrid',
                                    anchor: '100%',
                                    //id: 'currentTicketsGrid',
                                    itemId: 'currentTicketsGrid',
                                    //height: 300,
                                    flex: 1.4,
                                    collapsible: true,
                                    store: 'ticketCurrentStore'
                                },
                                {
                                    xtype: 'actionCommentGrid',
                                    //height: 250,
                                    flex: 1,
                                    itemId: 'currentActionsGrid',
                                    collapsible: true,
                                    store: 'actionstoTicketCurrent'
                                },
                                {
                                    xtype: 'descriptionToCurrentTicket',
                                    //height: 300,
                                    flex: 1,
                                    collapsible: true,
                                    itemId: 'descriptionToCurrentTicketPanel'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    width: 220,
                    activeItem: 0,
                    layout: {
                        type: 'accordion'
                    },
                    collapsible: true,
                    title: 'Menü',
                    border: false,
                    split: true,
                    region: 'west',
                    items: [
                        {
                            xtype: 'panel',
                            width: 220,
                            activeItem: 0,
                            collapsed: false,
                            iconCls: 'report',
                            layout: {
                            	type: 'fit'
                            },
                            title: 'Support Tickets',
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    vertical: true,
                                    border: false,
                                    items: [
                                        {
                                            xtype: 'button',
                                            iconCls: 'report_add',
                                            text: 'Neues Ticket',
                                            tooltip: 'Erstellt ein neues Support Ticket ...',
                                            listeners: {
                                                click: {
                                                    fn: me.onNewTicketbuttonClick,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
				                            xtype: 'button',
				                            iconCls: 'search',
				                            text: 'Suche nach Tickets',
				                            tooltip: '&Ouml;ffnet ein Formular zur Suche ...',
				                            listeners: {
                                                click: {
                                                    fn: me.onPressSearch,
                                                    scope: me
                                                }
                                            }
				                        }
                                    ]
                                }
                            ],
                            items: [
                               /* {
                                    xtype: 'textfield',
                                    width: 200,
                                    name: 'search',
                                    fieldLabel: '',
                                    emptyText: 'Suchbegriff eingeben ...',
                                    listeners: {
                                        specialkey: {
                                            fn: me.onPressSearch,
                                            scope: me
                                        }
                                    }
                                },*/
                                {                                   
                                    xtype: 'allTicketsGrid',
                                    title: 'Tickets (letzten 24h)',
                                    itemId: 'tickets24hours',
                                    height: 400,
                                    autoScroll: true,
                                    width: 220,
                                    overflow: 'auto',
                                    forceFit: true,
                                    store: 'ticket24HoursStore',
                                    listeners: {
                                    	beforerender: function(component, options) {
                                    		var t = component.getDockedItems();
                                    			t[0].down('#reloadButton').text = '';
                                    	}
                                    },
                                    columns: [{
					                    xtype: 'gridcolumn',
					                    itemId: 'ticketNumberColumn',
					                    width: 75,
					                    hidden: true,
					                    dataIndex: 'ticketNumber',
					                    text: 'Nr.:'
					                },{
					                    xtype: 'gridcolumn',
					                    itemId: 'titleColumn',
					                   // width: 200,
					                    dataIndex: 'title',
					                    text: 'Kurzbeschreibung'
					                }]                                    
                                }]
                        },
                        {
                            xtype: 'panel',
                            id: 'panelStatistics',
                            collapsed: true,
                            iconCls: 'chart_pie',
                            title: 'Statistiken',
                            layout: {
                            	type: 'fit'
                            },
                             dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            border: false,
                            vertical: true,
	                            items: [
	                                {
	                                    xtype: 'button',
	                                    iconCls: 'chart_pie',
	                                    text: 'Ticket Statistik',
	                                    listeners: {
	                                        click: {
	                                            fn: me.pressTicketStatistic,
	                                            scope: me
	                                        }
	                                    }
	                                },
	                                {
	                                    xtype: 'button',
	                                    iconCls: 'chart_bar',
	                                    text: 'Mitarbeiter Statistik',
	                                    itemId: 'pressStaffTicketStatistic',
	                                    hidden: true,
	                                    listeners: {
	                                        click: {
	                                            fn: me.pressStaffTicketStatistic,
	                                            scope: me
	                                        }
	                                    }
	                                },
	                                {
	                                    xtype: 'button',
	                                    iconCls: 'chart_bar',
	                                    itemId: 'pressCustomerTicketStatistic',
	                                    text: 'Kunden Statistik',
	                                     listeners: {
	                                        click: {
	                                            fn: me.pressCustomerTicketStatistic,
	                                            scope: me
	                                        }
	                                    }
	                                }
	                            ]
	                        }
	                    ]
                        },
                       /* {
                            xtype: 'panel',
                            id: 'panelCalendar',
                            collapsed: true,
                            iconCls: 'calendar',
                            title: 'Kalender (Beta)',
                            items: [
                                {
                                    xtype: 'panel',
                                    border: 'false',
                                    iconCls: 'calendar',
                                    title: 'Kalender',
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    iconCls: 'calendar',
                                                    text: 'Kalender anzeigen'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },*/
                        {
                            xtype: 'panel',
                            id: 'panel_kb',
                            collapsed: true,
                            iconCls: 'knowledge_base',
                            title: 'Knowledge-Base (Beta)',
                             dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    vertical: true,
                                    border: false,
                                    items: [
                                        {
                                            xtype: 'button',
                                            iconCls: 'knowledge_base',
                                            text: 'KB öffnen',
                                            tooltip: 'Öffnet die Knowledge-Base ...',
                                            listeners: {
                                                click: {
                                                    fn: me.pressShowKB,
                                                    scope: me
                                                }
                                            }
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            id: 'panelSettings',
                            collapsed: true,
                            iconCls: 'settings',
                            title: 'Einstellungen'
                        }
                    ]
                },
                {
                    xtype: 'toolbar',
                    border: 'false',
                    height: 40,
                    itemId: 'statusBarPanel',
                    frameHeader: false,
                    region: 'south',
                    ui: 'footer',
                    items: [{
                    	xtype: 'tbfill'
                    },{
                    	xtype: 'button',
		                text: 'Version ' + programVersion,
		                handler: function () {
		                    Ext.MessageBox.show({
		                        title: 'Version ' + programVersion,
		                        msg: '<b>Customer Support Ticket Tool (CSTT) - <a href="pdf/changelog.pdf" target="_blank">Changelog</a></b><br /><br />Version: ' + programVersion + ' vom ' + releaseDate + '<br /><br /><a href="mailto:michael.scharrer@cordaware.com?subject=Customer%20Support%20Ticket%20Tool">Kontakt</a>',
		                        buttons: Ext.MessageBox.OK,
		                        icon: Ext.MessageBox.INFO
		                    });
		
		                }
		
		            }
		            ] 
                },
                {
                    xtype: 'toolbar',
                    height: 40, // neptune
                    // height: 30,
                    itemId: 'topToolbar',
                    region: 'north',
                    //style: 'background-image:url("images/layout/banner-grau.png");',
                    items: [
                        {
                            xtype: 'button',
                            iconCls: 'house',
                            text: 'Home',
                            tooltip: 'Home',
                            listeners: {
                                click: {
                                    fn: me.pressHomeButton,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'splitbutton',
                            iconCls: 'report',
                            text: 'Support Tickets',
                            menu: {
                                xtype: 'menu',
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        iconCls: 'report_add',
                                        text: 'Neues Ticket anlegen',
                                        listeners: {
                                            click: {
                                                fn: me.pressNewTicket,
                                                scope: me
                                            }
                                        }
                                    },
                                    {
                                        xtype: 'menuitem',
                                        iconCls: 'report',
                                        text: 'Support Tickets',
                                        listeners: {
                                            click: {
                                                fn: me.pressSupportTicket,
                                                scope: me
                                            }
                                        }
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Ticket Historie',
                                        iconCls: 'report_red',
                                        menu: {
			                                xtype: 'menu',
			                                items: [
			                                {
			                                        xtype: 'menuitem',
			                                        text: 'AKM',
			                                        listeners: {
			                                            click: {
			                                                fn: me.pressTicketHistoryAKM,
			                                                scope: me
			                                            }
			                                        }
			                                    },
			                                    {
			                                        xtype: 'menuitem',
			                                        text: 'ASM',
			                                        listeners: {
			                                            click: {
			                                                fn: me.pressTicketHistoryASM,
			                                                scope: me
			                                            }
			                                        }
			                                    },
			                                    {
			                                        xtype: 'menuitem',
			                                        text: 'Javaclient',
			                                        listeners: {
			                                            click: {
			                                                fn: me.pressTicketHistoryJavaclient,
			                                                scope: me
			                                            }
			                                        }
			                                    }
			                                ]
			                            },
                                        listeners: {
                                            click: {
                                                fn: me.pressTicketHistory,
                                                scope: me
                                            }
                                        }
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Projektstatus',
                                        iconCls: 'flag_green',
                                        listeners: {
                                            click: {
                                                fn: me.pressProjectStatusOverview,
                                                scope: me
                                            }
                                        }
                                    },{
                                        xtype: 'menuitem',
                                        text: 'Zurückgestellte Tickets',
                                        iconCls: 'arrow_redo',
                                        listeners: {
                                            click: {
                                                fn: me.pressDeferredTickets,
                                                scope: me
                                            }
                                        }
                                    },{
                                        xtype: 'menuitem',
                                        text: 'Statistik',
                                        iconCls: 'chart_pie',
                                        listeners: {
                                            click: {
                                                fn: me.pressTicketStatistic,
                                                scope: me
                                            }
                                        }
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'splitbutton',
                            iconCls: 'database_table',
                            text: 'Kunden',
                            menu: {
                                xtype: 'menu',
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        iconCls: 'database_table',
                                        text: 'Kundenübersicht',
                                        listeners: {
                                            click: {
                                                fn: me.pressCustomerOverview,
                                                scope: me
                                            }
                                        }
                                    },
                                    {
                                        xtype: 'menuitem',
                                        iconCls: 'database_add',
                                        text: 'Neuen Kunden anlegen',
                                        hidden: true,
                                        listeners: {
                                            click: {
                                                fn: me.pressNewCustomer,
                                                scope: me
                                            }
                                        }
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'splitbutton',
                            text: 'Kontaktpersonen',
                            iconCls: 'group',
                            menu: {
                                xtype: 'menu',
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        iconCls: 'group',
                                        text: 'Kontaktpersonen-Übersicht',
                                        listeners: {
                                            click: {
                                                fn: me.pressContactOverview,
                                                scope: me
                                            }
                                        }
                                    },
                                    {
                                        xtype: 'menuitem',
                                        iconCls: 'user_add',
                                        hidden: true,
                                        text: 'Neue Kontaktperson anlegen',
                                        listeners: {
                                            click: {
                                                fn: me.pressNewContact,
                                                scope: me
                                            }
                                        }
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                                    xtype: 'button',
                                    text: 'Einstellungen',
                                    iconCls: 'settings',
                                    menu: {
	                                xtype: 'menu',
	                                items: [
	                                    /*{
	                                        xtype: 'menuitem',
	                                        text: 'Passwort &auml;ndern',
	                                        iconCls: 'application_key',
	                                        handler: function() {
	                                         Ext.widget('changePasswordWindow');
	                                        }
	                                    },*/
	                                    {
	                                        xtype: 'menuitem',
	                                        text: 'weitere Einstellungen ...',
	                                        iconCls: 'settings_ext',
	                                        handler: function() {
	                                         Ext.widget('settingsWindow');
	                                        }
	                                    }
	                                ]
                            }
                        },
                        /*	{
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            iconCls: 'user_go',
                            id: 'logoutButton_ext',
                            text: 'Abmelden',
                            tooltip: 'Abmelden',
                            listeners: {
                                click: {
                                    fn: me.onLogoutClick,
                                    scope: me
                                }
                            }
                        },*/
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            listeners: {
                                beforerender: {
                                    fn: function(btn) {
		                                    if(Ext.isSecure) {
		                            		btn.iconCls = 'key';
		                            		btn.setText("SSL");
		                            	} else {
		                            		btn.iconCls = '';
		                            		btn.setText("SSL: nein");
                            			}
                                    },
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            iconCls: 'user',
                            id: 'logoutButton',
                            listeners: {
                                click: {
                                    fn: me.onLogoutClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },
    
    ticketPanelCheckChanges: function() {
    	
    },
    
    customerChangesCouchDB: function(json, lengthRev) {	
    },
    
    ticketChangesCouchDB: function(json, lengthRev) {	
    },
    
    actionChangesCouchDB: function(json, lengthRev) {
    },
    
    getDocIDChanges: function(docID) {
    },
    
    couchDBChanges: function()  {
    },

    onNewTicketbuttonClick: function(button, e, options) {
    },
    
    onCurrentTicketsTabActive: function(abstractcomponent, options) {
    },

    onPressSearch: function(field, e, options) {
    },

    onStatusBarPanelAfterRender: function(abstractcomponent, options) {
    },

    pressHomeButton: function(button, e, options) {
    },

    pressNewTicket: function(item, e, options) {
    },

    pressSupportTicket: function(item, e, options) {
    },

    pressTicketHistory: function(item, e, options) {
    },

    pressProjectStatusOverview: function(item, e, options) {
    },
    
    pressDeferredTickets: function(item, e, options) {
    },
    
    pressTicketStatistic: function(item, e, options) {
    },
    
    pressStaffTicketStatistic: function(item, e, options) {
    },
    
    pressCustomerTicketStatistic: function(item, e, options) {
    },

    pressCustomerOverview: function(item, e, options) {
    },

    pressNewCustomer: function(item, e, options) {
    },

    pressContactOverview: function(item, e, options) {
    },

    pressNewContact: function(item, e, options) {
    },

    onLogoutClick: function(button, e, options) {
    },
    
    doCSTTLayout: function() {
    }

});