/*
 * File: app/view/overviewVersionGrid.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('cstt.view.overviewVersionGrid', {
    extend: 'cstt.view.ui.overviewVersionGrid',
    alias: 'widget.overviewVersionGrid',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    },

    onRefreshClick: function(button, e, options) {
        this.store.load();
    },

    onAddClick: function(button, e, options) {
        // Zeige Fenster zum Hinzufuegen einer neuen Version in der Versionsverwaltung
        var window = Ext.widget('createVersionWindow');
    },

    onDeleteClick: function(button, e, options) {
        selectVersion = this.getView().getSelectionModel().getSelection()[0];
        if (selectVersion) {

            // Bei Klick auf ja -> Eintrag loeschen
            function btnConfirm(btn){
                if (btn == 'yes') {

                    var rev = selectVersion.get('_rev');
                    //  console.log('rev id = ' + rev);
                    Ext.apply(this.store.proxy.extraParams, { 'rev': rev });
                    this.store.remove(selectVersion);


                    this.store.sync();
                    Ext.destroyMembers(this.store.proxy.extraParams, 'rev');
                    Ext.example.msg('Eintrag löschen', 'Daten werden neu geladen ...');
                    this.store.load(); 
                }
            }	

            // Bestätigung vom Benutzer	zum Löschen des Eintrages			
            Ext.Msg.show({
                title:'Löschen',
                msg: 'Möchten Sie diesen Eintrag wirklich löschen?',
                buttons: Ext.Msg.YESNO,
                fn: btnConfirm,
                icon: Ext.MessageBox.WARNING,
                scope: this
            });



        } else {
            Ext.MessageBox.show({
                title: 'Hinweis',
                msg: 'Bitte wählen Sie zuerst eine Version aus, die Sie löschen möchten.',
                buttons: Ext.MessageBox.OK,
                icon: Ext.MessageBox.INFO
            });
        }
    }

});