/*
 * File: app/view/showOneActionInWindow.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('cstt.view.showOneActionInWindow', {
    extend: 'cstt.view.ui.showOneActionInWindow',
    alias: 'widget.showOneActionInWindow',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    },

    onCloseClick: function(button, e, options) {
        this.close();
    },
    
    displayEmailTo: function(array, wHeight) {
                    
		var emailTo = "";
    	for (e = 0; e < array.length; e++) {
    	emailTo =  emailTo + array[e]+'<br/>';
    	
    	wHeight = wHeight + 15;
    	
    	}

    	this.down('#emailTo').setValue(emailTo);
    	this.setHeight(wHeight);
	
                    	
    },

    updateContent: function() {
        if(this.dataRecord.get('_id') !== 'null') {

            // Wait Message anzeigen	
            Ext.MessageBox.wait('Laden ...', 'Bitte warten ...');

            Ext.Ajax.request({
                method: 'GET',
                url: '../../'+this.dataRecord.get('_id'),
                // Header auf application/json setzen - CouchDB
                headers: {
                    'Content-Type': 'application/json; charset=utf-8'
                },
                scope: this,
                success: function (result, request ) {				
                    // Get JSON 
                    var json = Ext.JSON.decode(result.responseText);						

                    // Titel der Aktion anzeigen
                    if (json.title !== '') {
                        this.title = 'Aktion: ' + json.title;
                    } else {
                        this.title = 'Aktion anzeigen ...';
                    }

                    // Erstellt am Datum anzeigen	
                    var date = Ext.Date.parse(json.createdOn, 'Y-m-d H:i:s');	
                    var dateFormatted = Ext.Date.format(date, 'd.m.Y H:i:s');				
                    this.down('#date').setValue(dateFormatted);	


                    // Status Text rendern
                    var statusText = switchStatusText(parseInt(json.status));

                    if (statusText !== '') {
                        this.down('#action').setValue(statusText);
                    }
                    else {
                        if (json.title !== '' && json.title !== undefined) {
                            this.setTitle('Kommentar: ' + json.title);
                        }
                        else { 
                            this.setTitle('Kommentar anzeigen ...');
                        }
                        this.down('#action').setValue('<b>Aktion:</b>&nbsp;Kommentar<br />');
                    }

                    // Mitarbeiter Name anzeigen
                    this.down('#staffName').setValue(this.dataRecord.get('ownerConvert'));
                    
                    var wHeight = this.height;

                    if(json.emailTo !== undefined) {
                    	
                    	if(json.emailTo.length > 0 || json.emailTo !== '') {
                    
                    		
	                    	if (Ext.isArray(json.emailTo)) {
		                    	if (json.emailTo.length > 0) {
		                    	
		             				this.displayEmailTo(json.emailTo, wHeight);
		                    	}
	                    		
	                    		
	                    	} else {
	                    	
	                    		var stringEmail = json.emailTo;
	                    		var emailArr = new Array();
	                    		
	                    		emailArr = stringEmail.split(',');
	                    		
	                    		this.displayEmailTo(emailArr, wHeight);
	                    		
	                    	
	                    	
	                    	}
                    	
                    	}
                    	
                    	
                    }
                   

                    // reqFiles ausgewaehlt		
                    if (json.reqFiles !== undefined && json.reqFiles.length > 0 ) {
                        // Kommentar-Text anzeigen
                        this.down('#comment').update('<b>Geforderte Dateien:</b> ' + json.reqFiles + '<br /><br />' + json.comment);
                    }
                    else {
                        // Kommentar-Text anzeigen
                        this.down('#comment').update(json.comment);
                    }	

                    // Wait Message verbergen			
                    Ext.MessageBox.hide();
                    
                    this.doLayout();
                    
                    // Fenster anzeigen
                    this.show();
                    
                    
                    

                }
            });		
        }
    }

});