%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosFileTransfer_FileTransferSession
%% Source: /private/tmp/erlang-Y5fv/otp-OTP_R16B02/lib/cosFileTransfer/src/CosFileTransfer.idl
%% IC vsn: 4.3.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSFILETRANSFER_FILETRANSFERSESSION_HRL).
-define(COSFILETRANSFER_FILETRANSFERSESSION_HRL, true).




-endif.


