%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTransactions_RecoveryCoordinator
%% Source: /private/tmp/erlang-Y5fv/otp-OTP_R16B02/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.3.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTRANSACTIONS_RECOVERYCOORDINATOR_HRL).
-define(COSTRANSACTIONS_RECOVERYCOORDINATOR_HRL, true).




-endif.


